[package]
name = "yaml-std"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
easy-config-store = { path = "../..", default-features = false, features = [
	"yaml",
] }
serde = { version = "1.0.219", features = ["derive"] }
